_target_: src.app.infer.Inferer

exp_name: Brats21_Test
checkpoint_path: /work/hpc/spine-segmentation/logs/train/runs/brats/checkpoints/last.ckpt

data_name: BraTS2021

data_loader:
  _target_: torch.utils.data.DataLoader

  dataset:
    _target_: src.data.components.spider_dataset.SpiderTransformedDataset

    dataset:
      _target_: src.data.components.spider_dataset.SpiderDataset
      data_dir: /data/hpc/spine/dataset/
      json_path: /data/hpc/spine/jsons/brats21_folds_test.json ##/data/hpc/spine/jsons/brats21_folds_test.json

    transform:
      _target_: monai.transforms.Compose
      transforms:
        - _target_: monai.transforms.LoadImaged
          keys: [image, label]
          image_only: False

        - _target_: monai.transforms.ConvertToMultiChannelBasedOnBratsClassesd
          keys: [label]

        # - _target_: monai.transforms.Resized
        #   keys: [image, label]
        #   spatial_size: [96, 96, 96]

        - _target_: monai.transforms.NormalizeIntensityd
          keys: image
          nonzero: True
          channel_wise: True

        - _target_: monai.transforms.ToTensord
          keys: [image, label]

  batch_size: 2
  num_workers: 4
  pin_memory: False
  shuffle: False
  collate_fn: ## can delete?
    _target_: monai.data.utils.list_data_collate
    _partial_: true

net:
  _target_: monai.networks.nets.SwinUNETR
  img_size: 128 ##96
  in_channels: 4 ## important!!!!
  out_channels: 3
  feature_size: 48
  drop_rate: 0.0
  attn_drop_rate: 0.0
  dropout_path_rate: 0.0
  use_checkpoint: true

model_inferer:
  _target_: monai.inferers.sliding_window_inference
  _partial_: true
  roi_size: [96, 96, 96] ##[roi_size_x, roi_size_y, roi_size_z]
  sw_batch_size: 1 ##batch size for sliding window inference
  overlap: 0.6 ##overlap for sliding window inference

device: cuda