_target_: src.models.spider_semantic_module.SpiderLitModule

defaults:
  - optimizer: adam
  - scheduler: warmup_cosine

net:
  _target_: monai.networks.nets.SwinUNETR
  img_size: [32, 192, 192]
  in_channels: 1
  out_channels: 3
  feature_size: 48 # 36 ##48
  use_checkpoint: null

# compile model for faster training with pytorch 2.0
compile: false

sw_batch_size: 1
roi_x: 32
roi_y: 192 #160
roi_z: 192
infer_overlap: 0.5