_target_: src.models.spider_semantic_module.SpiderLitModule

defaults:
  - optimizer: adam
  - scheduler: warmup_cosine

# net:
#   _target_: monai.networks.nets.SwinUNETR
#   img_size: [32, 192, 192] ## patch size
#   in_channels: 1
#   out_channels: 3
#   feature_size: 36 ##48
#   use_checkpoint: null


net:
  _target_: monai.networks.nets.AttentionUnet
  spatial_dims: 3
  in_channels: 1
  out_channels: 3
  channels: [16, 32, 64, 128, 256, 512]
  strides: [2, 2, 2, 2, 2]


# compile model for faster training with pytorch 2.0
compile: false

sw_batch_size: 4
roi_x: 32
roi_y: 256 #160
roi_z: 256
infer_overlap: 0.5