wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1719818229.0
    t:
      1:
      - 1
      - 5
      - 11
      - 35
      - 41
      - 48
      - 49
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.10.13
      5: 0.16.6
      6: 4.37.2
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
